Improve the java bindings
As suggested by Matthew Johnson <mjj29@debian.org>:
  - the java package doesn't need to depend on JVMs (since we don't ship
    any program, just the libraries)
  - the build system should always use the same JDK, in order to
    generate identical build results (as much as possible)

Also fix the long description for the package.

diff --git a/debian/ant-wrapper b/debian/ant-wrapper
--- a/debian/ant-wrapper
+++ b/debian/ant-wrapper
@@ -1,16 +1,9 @@
 #!/bin/sh
 
-BASE_NAME="/usr/lib/jvm/java"
+JAVA_HOME="/usr/lib/jvm/java-6-openjdk"
 
-for JAVA_IMPL in 6-openjdk 6-sun 1.5.0-sun; do
-    if [ -d "${BASE_NAME}-${JAVA_IMPL}" ]; then
-        JAVA_HOME="${BASE_NAME}-${JAVA_IMPL}"
-        break
-    fi
-done
-
-if [ -z "$JAVA_HOME" ]; then
-    echo "Can't find a supported JDK" 1>&2
+if [ ! -d "$JAVA_HOME" ]; then
+    echo "Can't find java-6-openjdk, please check the build-depends" 1>&2
     exit 1
 fi
 
